### ISSUE TITLE
Outdated Information in Section 3.3.5 - Collecting Per-task Heap Usage Statistics

### ISSUE THREAD

**Issue by zylalx1** [FreeRTOS/FreeRTOS-Kernel-Book#100]
In Section 3.3.5, titled "Collecting Per-task Heap Usage Statistics," the book mentions features that may be added to the kernel in the future (configTRACK_TASK_MEMORY_ALLOCATIONS etc. ). However, based on the discussion in [PR #353](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/353), it appears that this feature was ultimately not accepted into the FreeRTOS kernel.

To avoid potential confusion for readers, could this section either be updated to reflect the current status or be removed if the feature is no longer planned?

**Comment by aggarg** [comment]
Thank you  for reporting this. The following PR updates the mentioned section and also adds an example - https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/pull/101.
