### ISSUE TITLE
FreeRTOS-Kernel Book

### ISSUE THREAD

**Issue by amazonKamath** [FreeRTOS/FreeRTOS-Kernel-Book#24]
Publish a new edition of the FreeRTOS kernel book on FreeRTOS.org with updates to all existing chapters based on FreeRTOS kernel v10. ([Mastering the FreeRTOS Real Time Kernel - a Hands On Tutorial Guide](https://www.freertos.org/fr-content-src/uploads/2018/07/161204_Mastering_the_FreeRTOS_Real_Time_Kernel-A_Hands-On_Tutorial_Guide.pdf))

**Comment by sirnish** [comment]
FreeRTOS Kernel book is now available on github [freertos-kernel-book](https://github.com/FreeRTOS/freertos-kernel-book). Work is in progress to update the content.
