### ISSUE TITLE
Incorrect Chapter Reference

### ISSUE THREAD

**Issue by jdbaptista** [FreeRTOS/FreeRTOS-Kernel-Book#75]
In Section 7.5.1, the third bullet point about the return value of xSemaphoreCreateCounting states, "Chapter 2 provides more information on heap memory management." I believe it should instead reference Chapter 3 as Chapter 2 is 'The FreeRTOS Kernel Distribution'.

**Comment by kar-rahul-aws** [comment]
Hi @jdbaptista 
Thanks for pointing out the mistake. We have updated it and raised a [PR](https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/pull/76)
