### ISSUE TITLE
Missing bracket in ch. 10

### ISSUE THREAD

**Issue by g-berthiaume** [FreeRTOS/FreeRTOS-Kernel-Book#85]
It seems like this code example is missing a `}` 

https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/46f033eda4ccf4873ba01176d68824bd4661570e/ch10.md?plain=1#L1531

Thanks for the book. 
It's a great read so far.

**Comment by g-berthiaume** [comment]
> We are pleased to hear the positive feedback regarding the book. 
Glad to heard it!

> Please keep suggesting the changes you would wish to see , which helps us in improving the quality of the book. 
I'll do my best.

**Comment by aggarg** [comment]
> I would also suggest reformating the entier code block: The code indentation apprears to be broken too.

Thank you for pointing out. We have fixed it.
