### ISSUE TITLE
Question about the stream buffer API

### ISSUE THREAD

**Issue by g-berthiaume** [FreeRTOS/FreeRTOS-Kernel-Book#86]
Hi !
I just finished reading the excellent [chapter 10](https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/main/ch10.md#10-task-notifications) and I'm surprised that it does not mention [stream and message buffer](https://www.freertos.org/RTOS-stream-message-buffers.html). To my understanding of the [notification documentation](https://www.freertos.org/RTOS-task-notifications.html) they are built on top of them.

Is their usage deprecated over the TaskNotification API ?

Best,
Gabriel

**Comment by kar-rahul-aws** [comment]
Hi @g-berthiaume 
We plan to add  [stream and message buffer](https://www.freertos.org/RTOS-stream-message-buffers.html) in the book later on, it is in our backlog and we will update it on best effort basis.

**Comment by g-berthiaume** [comment]
Make sense. Thanks for your answer.
